FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /otp-service ./cmd/api

FROM alpine:latest
COPY --from=builder /otp-service /otp-service
EXPOSE 8084
CMD ["/otp-service"]
